name: cronyism

on:
  push:
    branches:
      - master
      - test
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo repository content
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.NEPOTISM_REPO }} 
          token: ${{ secrets.NEPOTISM_TOKEN }}
      - name: setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: | 
          cd src/py3x
          for d in `ls`
          do
            cd "$d"
            python -m pip install -r requirements.txt
            python run.py
            cd ..
          done
        env:
          NEPOTISM_KEY: ${{ secrets.NEPOTISM_KEY }} 

